require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1
  DisplayCopNames: true
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - bin/**
    - vendor/bundle/**/*

# Per team developer playbook
RSpec/MultipleMemoizedHelpers:
  Enabled: false

# Layout
Layout/LineLength:
  Max: 150

# Metrics
Metrics/AbcSize:
  Max: 23
Metrics/BlockLength:
  Max: 43
Metrics/ClassLength:
  Max: 136
Metrics/CyclomaticComplexity:
  Max: 8
Metrics/MethodLength:
  Max: 18

# Naming
Naming/PredicateName:
  NamePrefix:
    - has